#!/bin/bash
#$ -cwd 

source activate snakemake_env

#PATH=$PATH:/net/beliveau/vol1/home/eaguil/anaconda3/envs/snakemake_tutorial/bin
#PATH=$PATH:/net/beliveau/vol1/home/eaguil/miniconda3/envs/tigerfish/bin

snakemake --configfile config.yml --use-conda --conda-prefix /net/beliveau/vol1/home/eaguil/envs --cluster "qsub -cwd -l mfree={params.mfree} -l h_rt={params.h_rt} -R y -e ./log -o ./log" --jobs 10 --latency-wait 180

