#path to the jellyfish file
jf_file: "../../../../tigerfish_jf/hg38_tigerfish_18.jf"

#path to the entire chromosome
chr_path: "../../../../../../../reference/Assemblies/hg38_bp_noheader/"

samples: 
    - "chr1"
    - "chr2"
    - "chr3"
    - "chr4"
    - "chr5"
    - "chr6"
    - "chr7"
    - "chr8"
    - "chr9"
    - "chr10"
    - "chr11"
    - "chr12"
    - "chr13"
    - "chr14"
    - "chr15"
    - "chr16"
    - "chr17"
    - "chr18"
    - "chr19"
    - "chr20"
    - "chr21"
    - "chr22"
    - "chrX"
    - "chrY"

#all of the default parameters for the first script in the pipeline, repeat_ID
sliding_window:
    - 3000
    - 4000
    - 5000

threshold: 
    - 5
    - 8
    - 10

composition: 
    - 0.20
    - 0.35
    - 0.50

file_start:
    - 0 

#parameters in the specificity script
merlength:
    - 18

enrich_score:
    - 0.75
    - 0.80
    - 0.90
    - 0.95

copy_num:
    - 5
    - 10

local_val:
    - 2

global_val:
    - 2 
