

#path to the jf file for that individual chromosome
#you will need to likely run jf build as a pre-step before this
jf_file: "/net/beliveau/vol1/home/eaguil/beliveau/20_02_25_chain_pipeline/data/hg38_build_18mers.jf"

#path to the entire chromosome
chr_path: "../../../../reference/Assemblies/hg38_bp_noheader/"

#all of the default parameters for the first script in the pipeline, repeat_ID
sliding_window: [3000]
threshold: [10]
composition: [0.50]
file_start: [0]

#parameters in the specificity script
merlength: 18
enrich_score: 0.50
copy_num: 10

#for kmer filtering script
k_val: [10]
