
#path to genome fasta
probe_file: "data/dxz4_test_probe.tsv"

#directory for bowtie2 test alignment, replace path with entire genome bowtie2 build for expected behavior
bowtie2_dir: "../../main/main_pipeline/repeat_discovery_test/data/bt2/"

#option for probe design that directs pipeline implementation
assembly: "chm13"

#all chromosomes present in bed file or required for probe discovery are listed here
samples:
    - "chrX"

chrom_sizes_file: "data/test_chrom.sizes"

genome_windows: 50

bt2_alignments: 500000

seed_length: 15

model_temp: 69.5

bin_thresh: 5
