#path to jellyfish file
jf_file: "../../../tigerfish_jf/chm13_tigerfish_18.jf"

#path to chr
chr_path: "../../../../../../reference/Assemblies/chm13/"

samples:
    - "chr1"
    - "chr2"
    - "chr3"
    - "chr4"
    - "chr5"
    - "chr6"
    - "chr7"
    - "chr8"
    - "chr9"
    - "chr10"
    - "chr11"
    - "chr12"
    - "chr13"
    - "chr14"
    - "chr15"
    - "chr16"
    - "chr17"
    - "chr18"
    - "chr19"
    - "chr20"
    - "chr21"
    - "chr22"
    - "chrX"
window:
    - 3000
    - 4000
    - 5000
threshold: 
    - 5
    - 8
    - 10
composition:
    - 0.25
    - 0.35
    - 0.50
    - 0.75
file_start:
    - 0
merlength:
    - 18
enrich_score:
    - 0.75
    - 0.80
    - 0.90
    - 0.95
copy_num:
    - 5
    - 10
local_val:
    - 0
global_val:
    - 0
