
#path to genome fasta
probe_file: "data/dxz4_test_probe.tsv"

#directory for bowtie2 test alignment, replace path with entire genome bowtie2 build for expected behavior
bowtie2_dir: '../main_pipeline/expected_pipeline_output/repeat_ID_output/01_reference_files/02_bt2_idx/chm13'

#option for probe design that directs pipeline implementation
assembly: "chm13"

#all chromosomes present in bed file or required for probe discovery are listed here
samples:
    - "chrX"

chrom_sizes_file: "data/chm13.chrom.sizes"

genome_windows: 5000000

bt2_alignments: 500000

seed_length: 15

model_temp: 69.5

bin_thresh: 100
